### ISSUE TITLE
trying to run the gradio_app.py script from the ThreeStudio project. The script is encountering a RuntimeError while running, which suggests that there is an issue with tensors being on different devices (i.e., one tensor is on the CPU while another is on the GPU). You can try to ensure that all tensors are on the same device by calling the .to(device) method on your tensors, where device is either torch.device("cuda:0") or torch.device("cpu") Also ncountering a FileNotFoundError while trying to load a text embedding file for the prompt [a delicious hamburger] and the model stabilityai/stable-diffusion-2-1-base. This error suggests that the text embedding file was not found in the cache directory .threestudio_cache/text_embeddings/. I have try'd regenerating the text embeddings or checking if the cache directory is correctly set?

### ISSUE THREAD

**Issue by Abrahm1234** [threestudio-project/threestudio#254]
python gradio_app.py launch
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Global seed set to 0
[INFO] Loading Stable Diffusion ...
Spawn watcher for process 47890
[INFO] Loaded Stable Diffusion!
[INFO] Using 16bit Automatic Mixed Precision (AMP)
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] 
  | Name       | Type               | Params
--------------------------------------------------
0 | geometry   | VolumeGrid         | 5.0 M 
1 | material   | NoMaterial         | 0     
2 | background | TexturedBackground | 64    
3 | renderer   | NeRFVolumeRenderer | 0     
--------------------------------------------------
5.0 M     Trainable params
0         Non-trainable params
5.0 M     Total params
20.000    Total estimated model params size (MB)
[INFO] Validation results will be saved to ./outputs-gradio/sjc/@20230726-011245/save
[INFO] Using prompt [a delicious hamburger] and negative prompt []
[INFO] Using view-dependent prompts [side]:[side view of a delicious hamburger] [front]:[front view of a delicious hamburger] [back]:[backside view of a delicious hamburger] [overhead]:[overhead view of a delicious hamburger]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/abe/anaconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/abe/anaconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abe/threestudio/threestudio/models/prompt_processors/stable_diffusion_prompt_processor.py", line 91, in spawn_func
    text_embeddings = text_encoder(tokens.input_ids)[0]
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 823, in forward
    return self.text_model(
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 731, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 229, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
Traceback (most recent call last):
  File "/home/abe/threestudio/launch.py", line 249, in <module>
    main(args, extras)
  File "/home/abe/threestudio/launch.py", line 194, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 954, in _run
    call._call_lightning_module_hook(self, "on_fit_start")
  File "/home/abe/threestudio/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 144, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/abe/threestudio/threestudio/systems/sjc.py", line 44, in on_fit_start
    self.prompt_processor = threestudio.find(self.cfg.prompt_processor_type)(
  File "/home/abe/threestudio/threestudio/utils/base.py", line 63, in __init__
    self.configure(*args, **kwargs)
  File "/home/abe/threestudio/threestudio/models/prompt_processors/base.py", line 336, in configure
    self.load_text_embeddings()
  File "/home/abe/threestudio/threestudio/models/prompt_processors/base.py", line 392, in load_text_embeddings
    self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]
  File "/home/abe/threestudio/threestudio/models/prompt_processors/base.py", line 410, in load_from_cache
    raise FileNotFoundError(
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/80396c3f48e698a859d69c0669e61ba2.pt for model stabilityai/stable-diffusion-2-1-base and prompt [a delicious hamburger] not found.
Process 47890 not exists, watcher exits.

**Comment by vishalghor** [comment]
@Abrahm1234 I'm facing the same issue with the launch.py script :eyes:

**Comment by Abrahm1234** [comment]
It seems that I've have encountered an error while running a program. The error message suggests that a text embedding file for the model stabilityai/stable-diffusion-2-1-base and prompt [a DSLR photo of a squirrel-lizard hybrid,] was not found. The file is expected to be located at .threestudio_cache/text_embeddings/d7aff14a4650d71c28b77511e3a24b02.pt. I've tried to check if the file exists at the specified location or if there are any issues with the file path.                                                                                                                                                           
                                                                                                                                                             
                                                                                                                                                             Global seed set to 0
[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
[INFO] Using 16bit Automatic Mixed Precision (AMP)
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 3060') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] 
  | Name       | Type                           | Params
--------------------------------------------------------------
0 | geometry   | ImplicitVolume                 | 12.6 M
1 | material   | DiffuseWithPointLightMaterial  | 0     
2 | background | NeuralEnvironmentMapBackground | 448   
3 | renderer   | NeRFVolumeRenderer             | 0     
--------------------------------------------------------------
12.6 M    Trainable params
0         Non-trainable params
12.6 M    Total params
50.419    Total estimated model params size (MB)
[INFO] Validation results will be saved to outputs/dreamfusion-sd/a_DSLR_photo_of_a_squirrel-lizard_hybrid,@20230726-235528/save
[INFO] Using prompt [a DSLR photo of a squirrel-lizard hybrid,] and negative prompt []
[INFO] Using view-dependent prompts [side]:[a DSLR photo of a squirrel-lizard hybrid,, side view] [front]:[a DSLR photo of a squirrel-lizard hybrid,, front view] [back]:[a DSLR photo of a squirrel-lizard hybrid,, back view] [overhead]:[a DSLR photo of a squirrel-lizard hybrid,, overhead view]
Process SpawnProcess-1:
...
    self.text_embeddings = self.load_from_cache(self.prompt)[None, ...]
  File "/home/abe/threestudio/threestudio/models/prompt_processors/base.py", line 410, in load_from_cache
    raise FileNotFoundError(
FileNotFoundError: Text embedding file .threestudio_cache/text_embeddings/d7aff14a4650d71c28b77511e3a24b02.pt for model stabilityai/stable-diffusion-2-1-base and prompt [a DSLR photo of a squirrel-lizard hybrid,] not found.
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...

**Comment by Abrahm1234** [comment]
I found my first issue was with the hugging face login. also I was able to fix this issue by referring to: Following Example, but RuntimeError: Expected all tensors to be on the same device #236

**Comment by thuliu-yt16** [comment]
Should fix in #258. We recommend you use `transformers==4.28.1` to avoid potential errors.
