### ISSUE TITLE
error during pip install -r requirements.

### ISSUE THREAD

**Issue by andytriboletti** [threestudio-project/threestudio#283]
I'm failing on this line (pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2) using Ubuntu for Windows:

andy@andys-pc:~/threestudio$ pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
  Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-vu8gv1bc
  Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-vu8gv1bc
  Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Requirement already satisfied: rich>=12 in /home/andy/.local/lib/python3.10/site-packages (from nerfacc==0.5.2) (13.5.2)
Requirement already satisfied: torch in /home/andy/.local/lib/python3.10/site-packages (from nerfacc==0.5.2) (1.12.1+cu113)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/andy/.local/lib/python3.10/site-packages (from rich>=12->nerfacc==0.5.2) (2.16.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/andy/.local/lib/python3.10/site-packages (from rich>=12->nerfacc==0.5.2) (3.0.0)
Requirement already satisfied: typing-extensions in /home/andy/.local/lib/python3.10/site-packages (from torch->nerfacc==0.5.2) (4.7.1)
Requirement already satisfied: mdurl~=0.1 in /home/andy/.local/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=12->nerfacc==0.5.2) (0.1.2)
Building wheels for collected packages: nerfacc
  Building wheel for nerfacc (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [540 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/pdf.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/grid.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/pack.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/version.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/cameras2.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/__init__.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/cameras.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/volrend.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/scan.py -> build/lib.linux-x86_64-3.10/nerfacc
      copying nerfacc/data_specs.py -> build/lib.linux-x86_64-3.10/nerfacc
      creating build/lib.linux-x86_64-3.10/nerfacc/estimators
      copying nerfacc/estimators/occ_grid.py -> build/lib.linux-x86_64-3.10/nerfacc/estimators
      copying nerfacc/estimators/__init__.py -> build/lib.linux-x86_64-3.10/nerfacc/estimators
      copying nerfacc/estimators/prop_net.py -> build/lib.linux-x86_64-3.10/nerfacc/estimators
      copying nerfacc/estimators/base.py -> build/lib.linux-x86_64-3.10/nerfacc/estimators
      creating build/lib.linux-x86_64-3.10/nerfacc/cuda
      copying nerfacc/cuda/__init__.py -> build/lib.linux-x86_64-3.10/nerfacc/cuda
      copying nerfacc/cuda/_backend.py -> build/lib.linux-x86_64-3.10/nerfacc/cuda
      running egg_info
      creating nerfacc.egg-info
      writing nerfacc.egg-info/PKG-INFO
      writing dependency_links to nerfacc.egg-info/dependency_links.txt
      writing requirements to nerfacc.egg-info/requires.txt
      writing top-level names to nerfacc.egg-info/top_level.txt
      writing manifest file 'nerfacc.egg-info/SOURCES.txt'
      reading manifest file 'nerfacc.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'nerfacc/_cuda/csrc/include/*'
      warning: no files found matching 'nerfacc/_cuda/csrc/*'
      adding license file 'LICENSE'
      writing manifest file 'nerfacc.egg-info/SOURCES.txt'
      creating build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      copying nerfacc/cuda/csrc/camera.cu -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      copying nerfacc/cuda/csrc/grid.cu -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      copying nerfacc/cuda/csrc/nerfacc.cpp -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      copying nerfacc/cuda/csrc/pdf.cu -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      copying nerfacc/cuda/csrc/scan.cu -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc
      creating build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/data_spec.hpp -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/data_spec_packed.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_camera.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_contraction.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_cuda.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_grid.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_math.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      copying nerfacc/cuda/csrc/include/utils_scan.cuh -> build/lib.linux-x86_64-3.10/nerfacc/cuda/csrc/include
      running build_ext
      /home/andy/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.5) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
        warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
      /home/andy/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py:820: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 11.5
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'nerfacc.csrc' extension
      creating build/temp.linux-x86_64-3.10
      creating build/temp.linux-x86_64-3.10/nerfacc
      creating build/temp.linux-x86_64-3.10/nerfacc/cuda
      creating build/temp.linux-x86_64-3.10/nerfacc/cuda/csrc
      /usr/bin/nvcc -Inerfacc/cuda/csrc/include -I/home/andy/.local/lib/python3.10/site-packages/torch/include -I/home/andy/.local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/andy/.local/lib/python3.10/site-packages/torch/include/TH -I/home/andy/.local/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -c nerfacc/cuda/csrc/camera.cu -o build/temp.linux-x86_64-3.10/nerfacc/cuda/csrc/camera.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -O3 --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=csrc -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++14
      /usr/include/c++/11/type_traits(1406): error: type name is not allowed

      /usr/include/c++/11/type_traits(1406): error: type name is not allowed

      /usr/include/c++/11/type_traits(1406): error: identifier "__is_same" is undefined

**Comment by bennyguo** [comment]
seems something wrong with the nerfacc installation. you could try installing the pre-compiled wheel here: https://github.com/KAIR-BAIR/nerfacc#installation

<img width="791" alt="image" src="https://github.com/threestudio-project/threestudio/assets/19284678/0ecfd5fe-3e51-4f0e-aaed-111ab65d0a97">

**Comment by andytriboletti** [comment]
Following the instructions in this article: https://zenn.dev/shinya7y/articles/threestudio-prolificdreamer I was able to get it installed.

**Comment by jygkh** [comment]
I followed the instructions for https://zenn.dev/shinya7y/articles/threestudio-prolificdreamer

(threestudio) ryan@DESKTOP-81PKUNM:/mnt/d/python/threestudio-main$ python launch.py --config configs/prolificdreamer.yaml --train --gpu 0 system.prompt_processor.prompt="a DSLR photo of a delicious croissant" data.width=64 data.height=64
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
Seed set to 0
[INFO] Loading Stable Diffusion ...
model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 543/543 [00:00<00:00, 1.57MB/s]
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 911/911 [00:00<00:00, 6.12MB/s]
vae/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 553/553 [00:00<00:00, 4.56MB/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 613/613 [00:00<00:00, 6.24MB/s]
scheduler/scheduler_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 346/346 [00:00<00:00, 2.88MB/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:53<00:00, 6.28MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36G/1.36G [01:58<00:00, 11.5MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.46G/3.46G [04:27<00:00, 12.9MB/s]
Fetching 8 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [04:27<00:00, 33.49s/it]
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:18<00:00,  4.54s/it]
model_index.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 537/537 [00:00<00:00, 3.59MB/s]
vae/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 611/611 [00:00<00:00, 1.57MB/s]
scheduler/scheduler_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 345/345 [00:00<00:00, 2.64MB/s]
text_encoder/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 633/633 [00:00<00:00, 1.21MB/s]
unet/config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 939/939 [00:00<00:00, 5.22MB/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 335M/335M [00:29<00:00, 11.2MB/s]
model.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36G/1.36G [02:20<00:00, 9.66MB/s]
diffusion_pytorch_model.safetensors:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 2.72G/3.46G [03:32<00:58, 12.8MB/s]
Fetching 8 files:  62%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 5/8 [03:33<02:07, 42.67s/it]
Traceback (most recent call last):s:  39%|█████████████████████████████████████████████████████████████▋                                                                                                | 1.35G/3.46G [02:14<04:17, 8.18MB/s]
  File "/mnt/d/python/threestudio-main/launch.py", line 301, in <module>█████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 2.72G/3.46G [03:22<00:33, 22.6MB/s]
    main(args, extras)
  File "/mnt/d/python/threestudio-main/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/python/threestudio-main/threestudio/systems/base.py", line 45, in __init__
    self.configure()
  File "/mnt/d/python/threestudio-main/threestudio/systems/prolificdreamer.py", line 27, in configure
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/python/threestudio-main/threestudio/utils/base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "/mnt/d/python/threestudio-main/threestudio/models/guidance/stable_diffusion_vsd_guidance.py", line 103, in configure
    pipe_lora = StableDiffusionPipeline.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 908, in from_pretrained
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1488, in download
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 238, in snapshot_download
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/concurrent/futures/_base.py", line 456, in result
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/concurrent/futures/thread.py", line 58, in run
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 213, in _inner_hf_hub_download
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1461, in hf_hub_download
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 544, in http_get
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 483, in func_wrapper
OSError: [Errno 30] Read-only file system
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 666, in _exitfunc
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 590, in __call__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 894, in _cleanup
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 732, in rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 660, in _rmtree_safe_fd
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 683, in _rmtree_safe_fd
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 681, in _rmtree_safe_fd
OSError: [Errno 30] Read-only file system: '_remote_module_non_scriptable.cpython-311.pyc'
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 666, in _exitfunc
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 590, in __call__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 894, in _cleanup
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 738, in rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 736, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/tmphsdjs8g9wandb'
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 666, in _exitfunc
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 590, in __call__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 894, in _cleanup
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 738, in rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 736, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/tmp9qs5dn2cwandb-artifacts'
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 666, in _exitfunc
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 590, in __call__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 894, in _cleanup
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 738, in rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 736, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/tmp84yhii3gwandb-media'
Traceback (most recent call last):
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 666, in _exitfunc
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/weakref.py", line 590, in __call__
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 894, in _cleanup
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/tempfile.py", line 890, in _rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 738, in rmtree
  File "/home/ryan/miniconda3/envs/threestudio/lib/python3.11/shutil.py", line 736, in rmtree
OSError: [Errno 30] Read-only file system: '/tmp/tmpnc1b2a35wandb-media'
Bus error
