### ISSUE TITLE
[F glutil.cpp:338] eglInitialize() failed during refinement stage

### ISSUE THREAD

**Issue by tbergeron** [threestudio-project/threestudio#292]
I'm bumping into fatal error while trying to execute the refinement stage using the Docker setup on Ubuntu 22.04.2 LTS. On Amazon EC2 on a g4dn.xlarge instance. (NVIDIA T4 GPUs)

Here's an example of how I encounter this error using Magic3D/StableDiffusion:

I first run `python launch.py --config configs/magic3d-coarse-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a green racecar"`

Once it's done I try to refine: `python launch.py/ --config configs/magic3d-refine-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a green racecar" system.geometry_convert_from=outputs/magic3d-coarse-sd/a_green_racecar@20230824-193528/ckpts/last.ckpt`

And after a few minutes I get:

```
dreamer@57c4216163ef:~/threestudio$ python launch.py --config configs/magic3d-refine-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a green racecar" system.geometry_convert_from=outputs/magic3d-coarse-sd/a_green_race_car@20230827-162015/ckpts/last.ckpt
/home/dreamer/.local/lib/python3.10/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
Global seed set to 0
[INFO] Initializing geometry from a given checkpoint ...
[INFO] Automatically determined isosurface threshold: 4.317230701446533
[INFO] Automatically determined isosurface threshold: 4.642081260681152
[F glutil.cpp:338] eglInitialize() failed
Aborted (core dumped)
```

It says here that it could be a NVIDIA driver error and that I should install `libnvidia-gl`

https://github.com/NVlabs/nvdiffrast/issues/58

https://github.com/NVlabs/nvdiffrast/issues/51#issuecomment-954275825

Could it be as simple as adding that package in the Dockerfile?

**Comment by tbergeron** [comment]
Adding the package to Dockerfile doesn't work:

```
 > [threestudio  2/10] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     build-essential     curl     git     libegl1-mesa-dev     libgl1-mesa-dev     libgles2-mesa-dev     libnvidia-gl     libglib2.0-0     libsm6     libxext6     libxrender1     python-is-python3     python3.10-dev     python3-pip     nano     htop     wget     && rm -rf /var/lib/apt/lists/*:
0.356 Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
0.421 Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [458 kB]
0.464 Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
0.469 Get:4 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
0.907 Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [860 kB]
0.934 Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
1.045 Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
1.152 Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
1.214 Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
1.273 Get:10 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [983 kB]
1.358 Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [897 kB]
1.417 Get:12 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]
1.426 Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
2.372 Get:14 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
2.373 Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [923 kB]
2.389 Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1247 kB]
2.455 Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1136 kB]
2.517 Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]
2.520 Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [49.2 kB]
2.521 Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [25.6 kB]
3.363 Fetched 27.0 MB in 3s (8776 kB/s)
3.363 Reading package lists...
4.141 Reading package lists...
4.883 Building dependency tree...
5.017 Reading state information...
5.021 Package libnvidia-gl is a virtual package provided by:
5.021   libnvidia-gl-535 535.86.10-0ubuntu1
5.021   libnvidia-gl-525 525.125.06-0ubuntu1
5.021   libnvidia-gl-515 515.105.01-0ubuntu1
5.021   libnvidia-gl-530 530.30.02-0ubuntu1
5.021   libnvidia-gl-520 520.61.05-0ubuntu1
5.021   libnvidia-gl-535-server 535.54.03-0ubuntu0.22.04.1
5.021   libnvidia-gl-525-server 525.125.06-0ubuntu0.22.04.1
5.021   libnvidia-gl-470-server 470.199.02-0ubuntu0.22.04.1
5.021   libnvidia-gl-470 470.199.02-0ubuntu0.22.04.1
5.021   libnvidia-gl-450-server 450.248.02-0ubuntu0.22.04.1
5.021   libnvidia-gl-418-server 418.226.00-0ubuntu5~0.22.04.1
5.021   libnvidia-gl-390 390.157-0ubuntu0.22.04.2
5.021
5.025 E: Package 'libnvidia-gl' has no installation candidate
------
failed to solve: process "/bin/sh -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     build-essential     curl     git     libegl1-mesa-dev     libgl1-mesa-dev     libgles2-mesa-dev     libnvidia-gl     libglib2.0-0     libsm6     libxext6     libxrender1     python-is-python3     python3.10-dev     python3-pip     nano     htop     wget     && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
ubuntu@ip-172-31-23-1:~/threestudio/docker$
```

**Comment by thuliu-yt16** [comment]
I think you should specify the `context_type` to `cuda`. You can refer to the [documentation](https://github.com/threestudio-project/threestudio/blob/main/DOCUMENTATION.md).

**Comment by tbergeron** [comment]
> 

I will try with that parameter. If I understand right I should add `system.renderer.context_type=cuda` to the refinement command. I'll report the results here. Thank you!

**Comment by altava-sgp** [comment]
I got same error.
```shell
dreamer@2ef3133204b2:~/threestudio$ python launch.py --config outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/configs/parsed.yaml --export --gpu 0 resume=outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/ckpts/last.ckpt system.exporter_type=mesh-exporter
Global seed set to 0
[INFO] Loading Zero123 ...
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 12.31it/s]
[INFO] Loaded Stable Diffusion!
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] single image dataset: load image ./load/images/outter_1_clipdrop-background-removal_rgba.png torch.Size([1, 256, 256, 3])
[INFO] Restoring states from the checkpoint path at outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/ckpts/last.ckpt
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] Loaded model weights from the checkpoint at outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/ckpts/last.ckpt
/home/dreamer/.local/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:442: PossibleUserWarning: The dataloader, predict_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 20 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Predicting: 0it [00:00, ?it/s][F glutil.cpp:338] eglInitialize() failed
Aborted
dreamer@2ef3133204b2:~/threestudio$ python launch.py --config outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/configs/parsed.yaml --export --gpu 0 resume=outputs/zero123-simple/sds_256_outter_1_clipdrop-background-removal_rgba.png@20230905-115245/ckpts/last.ckpt system.exporter_type=mesh-exporter system.renderer.context_type=cuda
Global seed set to 0
Traceback (most recent call last):
  File "/home/dreamer/threestudio/launch.py", line 237, in <module>
    main(args, extras)
  File "/home/dreamer/threestudio/launch.py", line 105, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 45, in __init__
    self.configure()
  File "/home/dreamer/threestudio/threestudio/systems/zero123_simple.py", line 21, in configure
    super().configure()
  File "/home/dreamer/threestudio/threestudio/systems/base.py", line 290, in configure
    self.renderer = threestudio.find(self.cfg.renderer_type)(
  File "/home/dreamer/threestudio/threestudio/utils/base.py", line 100, in __init__
    self.cfg = parse_structured(self.Config, cfg)
  File "/home/dreamer/threestudio/threestudio/utils/config.py", line 122, in parse_structured
    scfg = OmegaConf.structured(fields(**cfg))
TypeError: NeRFVolumeRenderer.Config.__init__() got an unexpected keyword argument 'context_type'
```
![image](https://github.com/threestudio-project/threestudio/assets/133635323/a9035ed8-a2b0-4e6c-a122-2f5a52ee8053)

**Comment by thuliu-yt16** [comment]
system.exporter.context_type=cuda

**Comment by altava-sgp** [comment]
@thuliu-yt16 
I got it ! Thanks!
![image](https://github.com/threestudio-project/threestudio/assets/133635323/5c39fd4b-9aef-4d82-a736-993489f239f0)

**Comment by JackISODesign** [comment]
> system.exporter.context_type=cuda
I had the same issue as this thread.
This worked for me! Thank you.

**Comment by photon-garden** [comment]
Hi folks! I was running into this issue when running the refinement step for Magic123 on an Nvidia A10 from Lambda Labs and ended up needing to set `system.renderer.context_type=cuda`. (Setting `system.exporter.context_type=cuda` didn't help.)
