### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by wooj0216** [threestudio-project/threestudio#309]
I tried ProlificDreamer.

$ python launch.py --config configs/prolificdreamer.yaml --train --gpu 7 system.prompt_processor.prompt="a pineapple" data.width=64 data.height=64 data.batch_size=1

Traceback (most recent call last):
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/launch.py", line 272, in <module>
    main(args, extras)
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/launch.py", line 86, in main
    import threestudio
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, image, multiview, uncond
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/data/co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/data/uncond.py", line 13, in <module>
    from threestudio.utils.base import Updateable
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/utils/base.py", line 7, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/cvlab07/project/woojeong/wj_threestudio/threestudio/threestudio/utils/misc.py", line 5, in <module>
    import tinycudann as tcnn
  File "/home/anaconda3/envs/wj_threestudio/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/anaconda3/envs/wj_threestudio/lib/python3.9/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/anaconda3/envs/wj_threestudio/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

ImportError: /home/anaconda3/envs/wj_threestudio/lib/python3.9/site-packages/tinycudann_bindings/_86_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE

I thought it was because of torch and torchvision version problem, so I tried both cases, but it didn't work.

1. torch1.12.1+cu113
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
2. or torch2.0.0+cu118
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118

Why is this problem occuring? And how can I fix it?

**Comment by bennyguo** [comment]
This often happens when you first install the CUDA-related packages (tinycudann, nerfacc, nvdiffrast) and then accidentally install a different version of PyTorch. You can reinstall these three packages by
```
pip uninstall nerfacc tinycudann nvdiffrast
pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
pip install git+https://github.com/NVlabs/nvdiffrast.git
```
and see if it works.

**Comment by wooj0216** [comment]
Oh it worked! Thank you very much :)
