### ISSUE TITLE
Cuda Stream Error

### ISSUE THREAD

**Issue by hasan1292** [threestudio-project/threestudio#319]
Hi, when I run the default command given by you, I get the following error, Any idea how to solve? 

Error:
python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"
Traceback (most recent call last):
  File "/home/ukhalid/new_work/threestudio-main/launch.py", line 237, in <module>
    main(args, extras)
  File "/home/ukhalid/new_work/threestudio-main/launch.py", line 73, in main
    import threestudio
  File "/home/ukhalid/new_work/threestudio-main/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, image, multiview, uncond
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/uncond.py", line 13, in <module>
    from threestudio.utils.base import Updateable
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/base.py", line 7, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/misc.py", line 5, in <module>
    import tinycudann as tcnn
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann_bindings/_86_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE
(3s) ukhalid@dumey:~/new_work/threestudio-main$ python gradio_app.py launch
Traceback (most recent call last):
  File "/home/ukhalid/new_work/threestudio-main/gradio_app.py", line 18, in <module>
    from threestudio.utils.config import load_config
  File "/home/ukhalid/new_work/threestudio-main/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, image, multiview, uncond
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/uncond.py", line 13, in <module>
    from threestudio.utils.base import Updateable
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/base.py", line 7, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/misc.py", line 5, in <module>
    import tinycudann as tcnn
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann_bindings/_86_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE
(3s) ukhalid@dumey:~/new_work/threestudio-main$ python launch.py --config configs/dreamfusion-if.yaml --train --gpu 0 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"python launch.py --config configs/dreamfusion-sd.yaml --train --gpu 0 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"
Traceback (most recent call last):
  File "/home/ukhalid/new_work/threestudio-main/launch.py", line 237, in <module>
    main(args, extras)
  File "/home/ukhalid/new_work/threestudio-main/launch.py", line 73, in main
    import threestudio
  File "/home/ukhalid/new_work/threestudio-main/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/__init__.py", line 1, in <module>
    from . import co3d, image, multiview, uncond
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/co3d.py", line 17, in <module>
    from threestudio.data.uncond import (
  File "/home/ukhalid/new_work/threestudio-main/threestudio/data/uncond.py", line 13, in <module>
    from threestudio.utils.base import Updateable
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/__init__.py", line 1, in <module>
    from . import base
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/base.py", line 7, in <module>
    from threestudio.utils.misc import get_device, load_module_weights
  File "/home/ukhalid/new_work/threestudio-main/threestudio/utils/misc.py", line 5, in <module>
    import tinycudann as tcnn
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/ukhalid/miniconda3/envs/3s/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ukhalid/miniconda3/envs/3s/lib/python3.9/site-packages/tinycudann_bindings/_86_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator12recordStreamERKNS_7DataPtrENS0_10CUDAStreamE
(3s) ukhalid@dumey:~/new_work/threestudio-main$

**Comment by Piggy-ch** [comment]
pip uninstall tinycudann
