### ISSUE TITLE
Magic3D Refine Stage: Fail to build nvdiffrast_plugin_gl.so 

### ISSUE THREAD

**Issue by iszihan** [threestudio-project/threestudio#331]
Hello, I'm running the command for magic3d's refine stage after the coarse stage finished. However, I'm getting this error 

Traceback (most recent call last):                                                          [7/1850]
  File "launch.py", line 237, in <module>                                                           
    main(args, extras)                                                                              
  File "launch.py", line 105, in main                                                               
    system: BaseSystem = threestudio.find(cfg.system_type)(                                         
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/systems/base.py",
 line 45, in __init__                                                                               
    self.configure()                                                                                
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/systems/magic3d.py", line 23, in configure 
    super().configure()
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/systems/base.py", line 290, in configure
    self.renderer = threestudio.find(self.cfg.renderer_type)(
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/utils/base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/models/renderers/nvdiff_rasterizer.py", line 32, in configure
    self.ctx = NVDiffRasterizerContext(self.cfg.context_type, get_device())
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/utils/rasterize.py", line 10, in __init__
    self.ctx = self.initialize_context(context_type, device)
  File "/nfs/rhea.dgp/u8/c/zling/projects/3d-detailization/threestudio/threestudio/utils/rasterize.py", line 16, in initialize_context
    return dr.RasterizeGLContext(device=device)
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/torch/utils/cpp_exten
sion.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/torch/utils/cpp_exten
sion.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/1] g++-9 common.o glutil.o rasteri
ze_gl.o torch_bindings_gl.o torch_rasterize_gl.o -shared -lGL -lEGL -L/scratch/local/2023/zling/envs
/threestudio/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -lto
rch_cuda_cpp -ltorch -ltorch_python -L/scratch/local/2023/zling/envs/threestudio/lib64 -lcudart -o n
vdiffrast_plugin_gl.so
FAILED: nvdiffrast_plugin_gl.so 
g++-9 common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o -shared -lGL -lEGL -
L/scratch/local/2023/zling/envs/threestudio/lib/python3.8/site-packages/torch/lib -lc10 -lc10_cuda -
ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/scratch/local/2023/zling/envs/
threestudio/lib64 -lcudart -o nvdiffrast_plugin_gl.so
/usr/bin/ld: cannot find -lcudart: No such file or directory

I have /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudart.so, which I added to LD_LIBRARY_PATH but still get the same error.

Any clue on how to resolve it?

**Comment by iszihan** [comment]
This is solved by adding a link to the conda environment library folder.

 ln -s /usr/local/cuda/lib64/libcudart.so /scratch/local/2023/zling/envs/threestudio/lib64/libcudart.so
