### ISSUE TITLE
Magic123 on colab error--> ValueError: clip_camera_projection/zero123.py as defined in `model_index.json` does not exist in bennyguo/zero123-diffusers and is not a module in 'diffusers/pipelines'.

### ISSUE THREAD

**Issue by thevaibhavkute** [threestudio-project/threestudio#336]
Hello all, I am running Magic123 on google colab,
Yesterday it was working fine but today getting this error on using below command:

```
#Zero123 + Stable Diffusion, ~12GB VRAM
#data.image_path must point to a 4-channel RGBA image
#system.prompt_proessor.prompt must be specified
!python launch.py --config configs/magic123-coarse-sd.yaml --train --gpu 0 data.image_path=/content/threestudio/load/images/sedan_rgba.png system.prompt_processor.prompt="a sedan car"
```

Error log:

```
/usr/local/lib/python3.10/dist-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
2023-11-07 03:24:03.162371: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-07 03:24:03.162441: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-07 03:24:03.162485: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-07 03:24:05.849269: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Seed set to 0
[INFO] Loading Stable Diffusion ...
Loading pipeline components...: 100% 4/4 [00:10<00:00,  2.55s/it]
[INFO] Loaded Stable Diffusion!
[INFO] Loading Zero123 ...
Traceback (most recent call last):
  File "/content/threestudio/launch.py", line 237, in <module>
    main(args, extras)
  File "/content/threestudio/launch.py", line 105, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/content/threestudio/threestudio/systems/base.py", line 45, in __init__
    self.configure()
  File "/content/threestudio/threestudio/systems/magic123.py", line 26, in configure
    self.guidance_3d = threestudio.find(self.cfg.guidance_3d_type)(
  File "/content/threestudio/threestudio/utils/base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "/content/threestudio/threestudio/models/guidance/zero123_unified_guidance.py", line 96, in configure
    pipe = Zero123Pipeline.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1079, in from_pretrained
    cached_folder = cls.download(
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 1685, in download
    raise ValueError(
ValueError: clip_camera_projection/zero123.py as defined in `model_index.json` does not exist in bennyguo/zero123-diffusers and is not a module in 'diffusers/pipelines'.
```

Thanks in advance

**Comment by bennyguo** [comment]
The new version of diffusers breaks the converted zero123 checkpoint. Degrading diffusers to old versions by `pip install "diffusers<0.20"` solves this.
