### ISSUE TITLE
Gradio Pydantic Error

### ISSUE THREAD

**Issue by v4r4rth** [threestudio-project/threestudio#363]
Facing the following error while attempting to lauch the Gradio interface:

*(threestudio) root@a100-instance-ajna:~/threestudio# python3 gradio_app.py launch
Traceback (most recent call last):
  File "gradio_app.py", line 13, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/usr/local/lib/python3.8/dist-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/usr/local/lib/python3.8/dist-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/usr/local/lib/python3.8/dist-packages/gradio/components/annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "/usr/local/lib/python3.8/dist-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "/usr/local/lib/python3.8/dist-packages/gradio/data_classes.py", line 19, in <module>
    from pydantic import BaseModel, RootModel, ValidationError  # type: ignore
ImportError: cannot import name 'RootModel' from 'pydantic' (/usr/local/lib/python3.8/dist-packages/pydantic/__init__.cpython-38-x86_64-linux-gnu.so)*

Please suggest what I can do to fix this as I am a beginner..

**Comment by bennyguo** [comment]
see this issue https://github.com/threestudio-project/threestudio/issues/350
