### ISSUE TITLE
[fantasia3d] IndexError: amin(): Expected reduction dim 0 to have non-zero size.

### ISSUE THREAD

**Issue by yihui-he** [threestudio-project/threestudio#40]
```
✗ python launch.py --config configs/fantasia3d.yaml --train --gpu 0 system.prompt_processor.prompt="The leaning tower of Pisa" system.geometry.shape_init=ellipsoid system.geometry.shape_init_params="[0.3,0.3,0.8]"

2023-05-09 17:30:11.595037: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-09 17:30:12.266796: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Global seed set to 0
[INFO] ModelCheckpoint(save_last=True, save_top_k=-1, monitor=None) will duplicate the last checkpoint saved.
wandb: Currently logged in as: yihuihe. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.21
wandb: Run data is saved locally in ./wandb/run-20230509_173018-2ydyxkrz
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run blooming-fog-7
wandb: ⭐️ View project at https://wandb.ai/yihuihe/lightning_logs
wandb: 🚀 View run at https://wandb.ai/yihuihe/lightning_logs/runs/2ydyxkrz
/home/yihuihe/anaconda3/lib/python3.10/site-packages/lightning_fabric/connector.py:562: UserWarning: bf16 is supported for historical reasons but its usage is discouraged. Please set your precision to bf16-mixed instead!
  rank_zero_warn(
[INFO] Using bfloat16 Automatic Mixed Precision (AMP)
[INFO] GPU available: True (cuda), used: True
[INFO] TPU available: False, using: 0 TPU cores
[INFO] IPU available: False, using: 0 IPUs
[INFO] HPU available: False, using: 0 HPUs
[INFO] You are using a CUDA device ('NVIDIA GeForce RTX 4090') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
[INFO] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
[INFO] 
  | Name       | Type                 | Params
----------------------------------------------------
0 | geometry   | ImplicitSDF          | 12.6 M
1 | material   | NoMaterial           | 0     
2 | background | SolidColorBackground | 0     
3 | renderer   | NVDiffRasterizer     | 0     
----------------------------------------------------
12.6 M    Trainable params
0         Non-trainable params
12.6 M    Total params
50.417    Total estimated model params size (MB)
[INFO] Loading Stable Diffusion ...
[INFO] Loaded Stable Diffusion!
Initializing SDF to a(n) ellipsoid:: 100%|█████████████████████████████████████| 1000/1000 [00:02<00:00, 417.38it/s]
Sanity Checking: 0it [00:00, ?it/s]/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:430: PossibleUserWarning: The dataloader, val_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 20 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:430: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 20 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Epoch 0: : 848it [00:47, 17.85it/s]
Epoch 0: : 885it [00:49, 17.75it/s]Traceback (most recent call last):             File "/home/yihuihe/3d/threestudio/launch.py", line 160, in <module>
    main()
  File "/home/yihuihe/3d/threestudio/launch.py", line 147, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 520, in fit
    call._call_and_handle_interrupt(
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 559, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 935, in _run
    results = self._run_stage()
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 978, in _run_stage
    self.fit_loop.run()
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 220, in advance
    batch_output = self.manual_optimization.run(kwargs)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 90, in run
    self.advance(kwargs)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/manual.py", line 109, in advance
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 288, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 366, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/yihuihe/3d/threestudio/threestudio/systems/fantasia3d.py", line 69, in training_step
    out = self(batch)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yihuihe/3d/threestudio/threestudio/systems/fantasia3d.py", line 48, in forward
    render_out = self.renderer(**batch, render_normal=True, render_rgb=False)
  File "/home/yihuihe/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yihuihe/3d/threestudio/threestudio/models/renderers/nvdiff_rasterizer.py", line 46, in forward
    mesh = self.geometry.isosurface()
  File "/home/yihuihe/3d/threestudio/threestudio/models/geometry/base.py", line 176, in isosurface
    vmin, vmax = mesh_coarse.v_pos.amin(dim=0), mesh_coarse.v_pos.amax(dim=0)
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/yihuihe/3d/threestudio/launch.py:160 in <module>                       │
│                                                                              │
│   157                                                                        │
│   158                                                                        │
│   159 if __name__ == "__main__":                                             │
│ ❱ 160 │   main()                                                             │
│   161                                                                        │
│                                                                              │
│ /home/yihuihe/3d/threestudio/launch.py:147 in main                           │
│                                                                              │
│   144 │   │   system.set_resume_status(ckpt["epoch"], ckpt["global_step"])   │
│   145 │                                                                      │
│   146 │   if args.train:                                                     │
│ ❱ 147 │   │   trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)       │
│   148 │   │   trainer.test(system, datamodule=dm)                            │
│   149 │   elif args.validate:                                                │
│   150 │   │   # manually set epoch and global_step as they cannot be automat │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/trainer.py:520 in fit                                                     │
│                                                                              │
│    517 │   │   """                                                           │
│    518 │   │   model = _maybe_unwrap_optimized(model)                        │
│    519 │   │   self.strategy._lightning_module = model                       │
│ ❱  520 │   │   call._call_and_handle_interrupt(                              │
│    521 │   │   │   self, self._fit_impl, model, train_dataloaders, val_datal │
│    522 │   │   )                                                             │
│    523                                                                       │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/call.py:44 in _call_and_handle_interrupt                                  │
│                                                                              │
│    41 │   │   if trainer.strategy.launcher is not None:                      │
│    42 │   │   │   return trainer.strategy.launcher.launch(trainer_fn, *args, │
│    43 │   │   else:                                                          │
│ ❱  44 │   │   │   return trainer_fn(*args, **kwargs)                         │
│    45 │                                                                      │
│    46 │   except _TunerExitException:                                        │
│    47 │   │   _call_teardown_hook(trainer)                                   │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/trainer.py:559 in _fit_impl                                               │
│                                                                              │
│    556 │   │   │   model_provided=True,                                      │
│    557 │   │   │   model_connected=self.lightning_module is not None,        │
│    558 │   │   )                                                             │
│ ❱  559 │   │   self._run(model, ckpt_path=ckpt_path)                         │
│    560 │   │                                                                 │
│    561 │   │   assert self.state.stopped                                     │
│    562 │   │   self.training = False                                         │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/trainer.py:935 in _run                                                    │
│                                                                              │
│    932 │   │   # ----------------------------                                │
│    933 │   │   # RUN THE TRAINER                                             │
│    934 │   │   # ----------------------------                                │
│ ❱  935 │   │   results = self._run_stage()                                   │
│    936 │   │                                                                 │
│    937 │   │   # ----------------------------                                │
│    938 │   │   # POST-Training CLEAN UP                                      │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/trainer.py:978 in _run_stage                                              │
│                                                                              │
│    975 │   │   │   with isolate_rng():                                       │
│    976 │   │   │   │   self._run_sanity_check()                              │
│    977 │   │   │   with torch.autograd.set_detect_anomaly(self._detect_anoma │
│ ❱  978 │   │   │   │   self.fit_loop.run()                                   │
│    979 │   │   │   return None                                               │
│    980 │   │   raise RuntimeError(f"Unexpected state {self.state}")          │
│    981                                                                       │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /fit_loop.py:201 in run                                                      │
│                                                                              │
│   198 │   │   while not self.done:                                           │
│   199 │   │   │   try:                                                       │
│   200 │   │   │   │   self.on_advance_start()                                │
│ ❱ 201 │   │   │   │   self.advance()                                         │
│   202 │   │   │   │   self.on_advance_end()                                  │
│   203 │   │   │   │   self._restarting = False                               │
│   204 │   │   │   except StopIteration:                                      │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /fit_loop.py:354 in advance                                                  │
│                                                                              │
│   351 │   │   assert self._data_fetcher is not None                          │
│   352 │   │   self._data_fetcher.setup(combined_loader)                      │
│   353 │   │   with self.trainer.profiler.profile("run_training_epoch"):      │
│ ❱ 354 │   │   │   self.epoch_loop.run(self._data_fetcher)                    │
│   355 │                                                                      │
│   356 │   def on_advance_end(self) -> None:                                  │
│   357 │   │   trainer = self.trainer                                         │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /training_epoch_loop.py:133 in run                                           │
│                                                                              │
│   130 │   │   self.on_run_start(data_fetcher)                                │
│   131 │   │   while not self.done:                                           │
│   132 │   │   │   try:                                                       │
│ ❱ 133 │   │   │   │   self.advance(data_fetcher)                             │
│   134 │   │   │   │   self.on_advance_end()                                  │
│   135 │   │   │   │   self._restarting = False                               │
│   136 │   │   │   except StopIteration:                                      │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /training_epoch_loop.py:220 in advance                                       │
│                                                                              │
│   217 │   │   │   │   │   # in automatic optimization, there can only be one │
│   218 │   │   │   │   │   batch_output = self.automatic_optimization.run(tra │
│   219 │   │   │   │   else:                                                  │
│ ❱ 220 │   │   │   │   │   batch_output = self.manual_optimization.run(kwargs │
│   221 │   │                                                                  │
│   222 │   │   self.batch_progress.increment_processed()                      │
│   223                                                                        │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /optimization/manual.py:90 in run                                            │
│                                                                              │
│    87 │   def run(self, kwargs: OrderedDict) -> _OUTPUTS_TYPE:               │
│    88 │   │   self.on_run_start()                                            │
│    89 │   │   with suppress(StopIteration):  # no loop to break at this leve │
│ ❱  90 │   │   │   self.advance(kwargs)                                       │
│    91 │   │   self._restarting = False                                       │
│    92 │   │   return self.on_run_end()                                       │
│    93                                                                        │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/loops │
│ /optimization/manual.py:109 in advance                                       │
│                                                                              │
│   106 │   │   trainer = self.trainer                                         │
│   107 │   │                                                                  │
│   108 │   │   # manually capture logged metrics                              │
│ ❱ 109 │   │   training_step_output = call._call_strategy_hook(trainer, "trai │
│   110 │   │   del kwargs  # release the batch from memory                    │
│   111 │   │   self.trainer.strategy.post_training_step()                     │
│   112 │   │   result = self.output_result_cls.from_training_step_output(trai │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/train │
│ er/call.py:288 in _call_strategy_hook                                        │
│                                                                              │
│   285 │   │   return                                                         │
│   286 │                                                                      │
│   287 │   with trainer.profiler.profile(f"[Strategy]{trainer.strategy.__clas │
│ ❱ 288 │   │   output = fn(*args, **kwargs)                                   │
│   289 │                                                                      │
│   290 │   # restore current_fx when nested context                           │
│   291 │   pl_module._current_fx_name = prev_fx_name                          │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/pytorch_lightning/strat │
│ egies/strategy.py:366 in training_step                                       │
│                                                                              │
│   363 │   │   """                                                            │
│   364 │   │   with self.precision_plugin.train_step_context():               │
│   365 │   │   │   assert isinstance(self.model, TrainingStep)                │
│ ❱ 366 │   │   │   return self.model.training_step(*args, **kwargs)           │
│   367 │                                                                      │
│   368 │   def post_training_step(self) -> None:                              │
│   369 │   │   pass                                                           │
│                                                                              │
│ /home/yihuihe/3d/threestudio/threestudio/systems/fantasia3d.py:69 in         │
│ training_step                                                                │
│                                                                              │
│    66 │   │                                                                  │
│    67 │   │   loss = 0.0                                                     │
│    68 │   │                                                                  │
│ ❱  69 │   │   out = self(batch)                                              │
│    70 │   │   text_embeddings = self.prompt_processor(**batch)               │
│    71 │   │                                                                  │
│    72 │   │   if self.true_global_step < self.cfg.latent_steps:              │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:1501 in _call_impl                                                       │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /home/yihuihe/3d/threestudio/threestudio/systems/fantasia3d.py:48 in forward │
│                                                                              │
│    45 │   │   self.automatic_optimization = False                            │
│    46 │                                                                      │
│    47 │   def forward(self, batch: Dict[str, Any]) -> Dict[str, Any]:        │
│ ❱  48 │   │   render_out = self.renderer(**batch, render_normal=True, render │
│    49 │   │   return {                                                       │
│    50 │   │   │   **render_out,                                              │
│    51 │   │   }                                                              │
│                                                                              │
│ /home/yihuihe/anaconda3/lib/python3.10/site-packages/torch/nn/modules/module │
│ .py:1501 in _call_impl                                                       │
│                                                                              │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                      │
│   1502 │   │   # Do not call functions when jit is used                      │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []         │
│   1504 │   │   backward_pre_hooks = []                                       │
│                                                                              │
│ /home/yihuihe/3d/threestudio/threestudio/models/renderers/nvdiff_rasterizer. │
│ py:46 in forward                                                             │
│                                                                              │
│   43 │   │   **kwargs                                                        │
│   44 │   ) -> Dict[str, Any]:                                                │
│   45 │   │   batch_size = mvp_mtx.shape[0]                                   │
│ ❱ 46 │   │   mesh = self.geometry.isosurface()                               │
│   47 │   │                                                                   │
│   48 │   │   v_pos_clip: Float[Tensor, "B Nv 4"] = self.ctx.vertex_transform │
│   49 │   │   │   mesh.v_pos, mvp_mtx                                         │
│                                                                              │
│ /home/yihuihe/3d/threestudio/threestudio/models/geometry/base.py:176 in      │
│ isosurface                                                                   │
│                                                                              │
│   173 │   │   if self.cfg.isosurface_coarse_to_fine:                         │
│   174 │   │   │   with torch.no_grad():                                      │
│   175 │   │   │   │   mesh_coarse = self._isosurface(self.bbox)              │
│ ❱ 176 │   │   │   vmin, vmax = mesh_coarse.v_pos.amin(dim=0), mesh_coarse.v_ │
│   177 │   │   │   vmin_ = (vmin - (vmax - vmin) * 0.1).max(self.bbox[0])     │
│   178 │   │   │   vmax_ = (vmax + (vmax - vmin) * 0.1).min(self.bbox[1])     │
│   179 │   │   │   mesh = self._isosurface(torch.stack([vmin_, vmax_], dim=0) │
╰──────────────────────────────────────────────────────────────────────────────╯
IndexError: amin(): Expected reduction dim 0 to have non-zero size.
```

**Comment by bennyguo** [comment]
Hi! It seems that the scene becomes empty. What does the validation image look like?

**Comment by yihui-he** [comment]
I did another run. 
Epoch 0: : 3235it [05:29,  9.81it/s]
the is it3200-0.png :
![it3200-0](https://github.com/threestudio-project/threestudio/assets/10027339/6edde7c5-aede-437a-9d48-ab9d6fbe8715)

**Comment by bennyguo** [comment]
Error-free this time? Fantasia3D training is quite unstable, you may need some luck picking a good seed.

**Comment by yihui-he** [comment]
no, every time it failed with the same error.
This time 8237it
this is it8236-0.png
![it8236-0](https://github.com/threestudio-project/threestudio/assets/10027339/b2b87046-b75a-4c22-9017-a0606c72aebe)

**Comment by thuliu-yt16** [comment]
Could you provide information about your local environment? I couldn't reproduce the error with the given command.

**Comment by yihui-he** [comment]
it's a problem with my local environment package mismatches, thx

**Comment by bennyguo** [comment]
Good to hear!
