### ISSUE TITLE
Gradio not working

### ISSUE THREAD

**Issue by notdanilo** [threestudio-project/threestudio#441]
Gradio is not working

```
dreamer@9d615a31c0af:~/threestudio$ python gradio_app.py 
Traceback (most recent call last):
  File "/home/dreamer/threestudio/gradio_app.py", line 13, in <module>
    import gradio as gr
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/components/annotated_image.py", line 11, in <module>
    from gradio import processing_utils, utils
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/processing_utils.py", line 22, in <module>
    from gradio.data_classes import FileData, GradioModel, GradioRootModel
  File "/home/dreamer/.local/lib/python3.10/site-packages/gradio/data_classes.py", line 12, in <module>
    from fastapi import Request
  File "/home/dreamer/.local/lib/python3.10/site-packages/fastapi/__init__.py", line 5, in <module>
    from .applications import FastAPI
  File "/home/dreamer/.local/lib/python3.10/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/home/dreamer/.local/lib/python3.10/site-packages/fastapi/routing.py", line 6, in <module>
    from fastapi import params
  File "/home/dreamer/.local/lib/python3.10/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic import Schema
ImportError: cannot import name 'Schema' from 'pydantic' (/home/dreamer/.local/lib/python3.10/site-packages/pydantic/__init__.py)
```

**Comment by onevfall** [comment]
See this. https://github.com/threestudio-project/threestudio/issues/350 helped me slove it.
