### ISSUE TITLE
Docker dependency error

### ISSUE THREAD

**Issue by crystalthoughts** [threestudio-project/threestudio#474]
Hi , there seems to be an error with nerfacc:
``` ERROR [ 6/10] RUN pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2                             16.7s
------
 > [ 6/10] RUN pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2:
0.806 Defaulting to user installation because normal site-packages is not writeable
0.867 Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
0.869   Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-prhdt19_
0.880   Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-prhdt19_
3.687   Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
4.250   Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
4.250   Running command git submodule update --init --recursive -q
13.38   Preparing metadata (setup.py): started
16.30   Preparing metadata (setup.py): finished with status 'error'
16.30   error: subprocess-exited-with-error
16.30
16.30   × python setup.py egg_info did not run successfully.
16.30   │ exit code: 1
16.30   ╰─> [10 lines of output]
16.30       Traceback (most recent call last):
16.30         File "<string>", line 2, in <module>
16.30         File "<pip-setuptools-caller>", line 34, in <module>
16.30         File "/tmp/pip-req-build-prhdt19_/setup.py", line 123, in <module>
16.30           ext_modules=get_extensions() if not BUILD_NO_CUDA else [],
16.30         File "/tmp/pip-req-build-prhdt19_/setup.py", line 29, in get_extensions
16.30           from torch.utils.cpp_extension import CUDAExtension
16.30         File "/home/dreamer/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
16.30           from pkg_resources import packaging  # type: ignore[attr-defined]
16.30       ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/dreamer/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)
16.30       [end of output]
16.30
16.30   note: This error originates from a subprocess, and is likely not a problem with pip.
16.31 error: metadata-generation-failed
16.31
16.31 × Encountered error while generating package metadata.
16.31 ╰─> See above for output.
16.31
16.31 note: This is an issue with the package mentioned above, not pip.
16.31 hint: See above for details.
```

**Comment by fealty94** [comment]
add below code in Dockerfile
RUN pip install setuptools==69.5.1
after
RUN pip install --upgrade pip setuptools ninja
above code.
Then rebuild.
This problem is caused by setuptools version<70
