### ISSUE TITLE
ProlificDreamer: LoRAAttnProcessor got an unexpected keyword argument 'hidden_size'

### ISSUE THREAD

**Issue by QZhang2111** [threestudio-project/threestudio#499]
As shown in title, when I run "!python launch.py --config configs/prolificdreamer.yaml --train --gpu 0 system.prompt_processor.prompt="a pineapple""

I get the error:
Traceback (most recent call last):
  File "/workspace/threestudio/launch.py", line 301, in <module>
    main(args, extras)
  File "/workspace/threestudio/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/workspace/threestudio/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/workspace/threestudio/threestudio/systems/prolificdreamer.py", line 26, in configure
    self.guidance = threestudio.find(self.cfg.guidance_type)(self.cfg.guidance)
  File "/workspace/threestudio/threestudio/utils/base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "/workspace/threestudio/threestudio/models/guidance/stable_diffusion_vsd_guidance.py", line 177, in configure
    lora_attn_procs[name] = LoRAAttnProcessor(
TypeError: LoRAAttnProcessor.__init__() got an unexpected keyword argument 'hidden_size'

Has anyone encountered similar problems?

**Comment by QZhang2111** [comment]
Just download the diffusers version less than 0.20
